ManMon/urls.py
from django.conf.urls import url

from . import views

app_name = 'ManMon'

urlpatterns = [
    url(r'^$', views.callMainPage, name='mainpage'),
    url(r'^accountinput$', views.callAccountInput, name='callAccountInput'),
    url(r'^saveAccount$', views.saveAccount, name="saveAccount"),
    url(r'^history$', views.history, name='history'),
    url(r'^exportHistory$', views.getCSV, name='getCSV'),
    url(r'^insertType/$', views.callInsertType, name='callInsertType'),
    url(r'^saveType/$', views.saveType, name='saveType'),
    url(r'^uploadFile/$', views.upload_file, name="uploadFile"),
    url(r'^uploaded/$', views.handle_uploaded_file, name="uploaded"),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('ManMon.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^addQues/$', views.addQues, name='addQues'),
    url(r'^saveQues/$', views.saveQues, name='saveQues'),
    url(r'^(?P<question_id>[0-9]+)/addChoice/$', views.addChoice, name='addChoice'),
    url(r'^(?P<question_id>[0-9]+)/saveChoice/$', views.saveChoice, name='saveChoice'),
]

ManMon/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Account(models.Model):
    note = models.CharField(max_length=200)
    money = models.FloatField(default=0)
    type_note = models.CharField(max_length=200, default='salary')
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.pub_date

    def __str__(self):
        return self.type_note

    def __flo__(self):
        return self.money

    def __str__(self):
        return self.note

class TypeIncome(models.Model):
    type_income = models.CharField(max_length=200)
    
    def __str__(self):
        return self.type_income

class TypePayment(models.Model):
    type_payment = models.CharField(max_length=200)

    def __str__(self):
        return self.type_payment

ManMon/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

ManMon/views.py
import csv
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
#from somewhere import handle_uploaded_file
from .forms import UploadFileForm
from .models import Account, TypeIncome, TypePayment

# Create your views here.

def callMainPage(request): 
    account_list = Account.objects.order_by('-pub_date')

    #calulation the rest of money
    remain_money = 0
    for account in account_list :
        remain_money += account.money

    account_list = Account.objects.order_by('-pub_date')[:5]
    for account in account_list :
        if account.money < 0 :
            money = account.money
            account.money = (-1)*float(money)
    return render(request, 'ManMon/main.html',{'remain_money':remain_money,         
                  'account_list':account_list})

def callAccountInput(request):
    type_in_list = TypeIncome.objects.order_by('-type_income')
    type_pay_list = TypePayment.objects.order_by('-type_payment')

    return render(request, 'ManMon/accountInput.html', {'type_in_list':type_in_list,'type_pay_list':type_pay_list})

def saveAccount(request):
    try:
        note = request.POST['note']
        money = request.POST['money']
        type_note = request.POST['type']
        date = request.POST['dmy']
    except:
        note = ""
        money = ""
        type_note = ""
        date = ""
    if(request.POST['choice'] == 'payment'):
        money = (-1)*float(money)

    ac = Account(note = note, money = money, type_note = type_note, pub_date = date)
    ac.save()
    return render(request, 'ManMon/saveAccount.html',{'note':note, 'money':money, 'type_note':type_note, 'date':date})
   
def history(request):
    account_list = Account.objects.order_by('-pub_date')
    money_sum = 0
    for account in account_list :
        money_sum += account.money
    return render(request, 'ManMon/history.html', {'account_list':account_list, 'money_sum':money_sum})

def callInsertType(request):
    return render(request,"ManMon/insertType.html",'')

def saveType(request):
    if(request.POST['choice'] == 'income' ):
        try:        
            save_type = request.POST['type']
        except:
            in_type = ""
        else:
            save_type = TypeIncome(type_income = save_type)
            save_type.save()
    if(request.POST['choice'] == 'payment' ):
        try:
            save_type = request.POST['type']
        except:
            save_type = ""
        else:
            save_type = TypePayment(type_payment = save_type)
            save_type.save()
    return render(request, "ManMon/saveType.html",{'save_type':save_type})

def getCSV(request):
    account_list = Account.objects.order_by('pub_date')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="ManMon.csv"'

    writer = csv.writer(response)
    writer.writerow(['note', 'money', 'type', 'date'])
    for account in account_list :
        writer.writerow([account.note, account.money, account.type_note, account.pub_date])

    return response

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            instance = ModelWithFileField(file_field=request.FILES['file'])
            instance.save()
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

ManMon/templates/ManMon/accountInput.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>
<body>
<h1 style = "text-align: center;">Manage Your Money</h1>

    <form action="{% url 'ManMon:saveAccount' %}" method="post">
    {% csrf_token %}
        <p>
        Note:
        <input type="text" name="note"></p>
        <p>Money:
        <input type="number" name="money" step="any"></p>
        <p>Date:
        <input type="datetime-local" name="dmy"></p><br>
        
        <input type="radio" name="choice" value="income">
        <label style = "color:rgb(110, 101, 252);" >income</label>
        <p>Type:
        <select name="type">            
            {% for typeincome in type_in_list %}
                <option for="type_income{{ forloop.counter }}">{{ typeincome.type_income }}</option>
            {% endfor %}
        </select>
        </p><br>

        <input type="radio" name="choice" value="payment">
        <label style = "color:rgb(110, 101, 252);">payment</label>
        <p>Type:
        <select name="type">
            {% for typepayment in type_pay_list %}
                <option for="type_payment{{ forloop.counter }}">{{ typepayment.type_payment }}</option>
            {% endfor %}
        </select> 
        </p>
        <input type="submit" >
    </form>
<br>
</body>
<a href="{% url 'ManMon:mainpage' %}" class="circleBtn"> {{"back to main page"}} </a>

</body>
</html>

ManMon/templates/ManMon/chooseInOrPay.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>
<h2 style = "text-align: center;color:rgb(110, 101, 252);">Manage Your Money</h2>

    <p style = "font-size:130%;">Payment</p>
    <form action="{% url 'ManMon:callAccountInput' %}" method="post">
    {% csrf_token %}

        <input type="radio" name="choice" value="income">
        <label>income</label>
        <input type="radio" name="choice" value="payment">
        <label>payment</label>
        <input type="submit"> 
    </form>

<a href="{% url 'ManMon:mainpage' %}" class="circleBtn"> {{"back to main page"}} </a>

</body>
</html>

ManMon/templates/ManMon/history.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>
<style>

table {
    border-collapse: collapse;
    width: 50%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

tr:hover {background-color: #f5f5f5}
tr:nth-child(even) {background-color: #ff0055}

</style>

<h1 style="text-align:center">History</h1>

{% if account_list %}
<table border=1 style="width:50%;clear:both" align="center" bgcolor=#00bfff>
        <tr>
            <td>Note</td>
            <td>Money</td>
            <td>Type</td>
            <td>Date</td>
        </tr>
    {% for account in account_list %}
        <tr>
            <td>{{ account.note }}</td>
            <td>{{ account.money }} Baths</td>
            <td>{{ account.type_note }}</td>
            <td>{{ account.pub_date }}</td>
        </tr>
    {% endfor %}
        <tr>
            <td style="text-align: center;" colspan="5">money sum : {{ money_sum }} Baths</td>
        </tr>
    <a href="{% url 'ManMon:mainpage'%}" class="circleBtn">{{"back to main page"}}</a>
{% else %}
    <p> Insert your income</p>
{% endif %}


</body>
</html>

ManMon/templates/ManMon/insertType.html
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>

<style>
.button {
    background-color: #4CAF50; 
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    font-style: italic;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    cursor: pointer;
    border-radius: 75%;
}

.button:hover {
    background-color: #4CAF00;
}

</style>
<h1 style ="color:rgb(110, 101, 252);">Add Income Type</h1>

    <form action="{% url 'ManMon:saveType'%}" method="post">
    <input type="radio" name="choice" value="income">
    <label style ="color:rgb(110, 101, 252);">Income</label>
    <input type="radio" name="choice" value="payment">
    <label style ="color:rgb(110, 101, 252);">Payment</label><br>
    {% csrf_token %}
        <p style ="color:rgb(110, 101, 252);">
            Type:<input type="text" name="type">
            <input type="submit">
        </p>
        
    </form>

<a href="{% url 'ManMon:mainpage' %}" class="button"> back to main page</a>

</html>

ManMon/templates/ManMon/main.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>
<style>

table {
    border-collapse: collapse;
    width: 50%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

tr:hover {background-color: #f5f5f5}
tr:nth-child(even) {background-color: #ff0055}

</style>


<h1 style = "text-align: center;">Manage Your Money</h1>

<div class="btn-group">
  <a href="{% url 'ManMon:callAccountInput' %}" class="button" >{{"Account Input"}}</a>
  <a href="{% url 'ManMon:history' %}" class="button" >{{"history"}}</a>
  <a href="{% url 'ManMon:callInsertType' %}" class="button">{{"Insert Type"}}</a>
  <a href="{% url 'ManMon:getCSV' %} " class="button">{{"Export"}}</a>
  <a href="{% url 'ManMon:uploadFile'%}" class="button">{{"Upload"}}</a>
</div>

<br>
<table border=1 style="width:50%;clear:both" align="center" bgcolor=#00bfff>
        <tr>
            <td>Note</td>
            <td>Money</td>
            <td>Type</td>
            <td>Date</td>
        </tr>
    {% for account in account_list %}
        <tr>
            <td>{{ account.note }}</td>
            <td>{{ account.money }} Baths</td>
            <td>{{ account.type_note }}</td>
            <td>{{ account.pub_date }}</td>
        </tr>
    {% endfor %}
        <tr>
            <td style="text-align: center;" colspan="5">money sum : {{ remain_money }} Baths</td>
        </tr>
</body>
</html>

ManMon/templates/ManMon/saveAccount.html
<!DOCTYPE html>
{% load static %}
<html>
<h1 style = "text-align:center; font-size:330%;">Manage Your Money</h1>
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<h1>You're already save:</h1>
<p>Note : {{note}}</p>
<p>Type : {{note_type}}</p>
<p>Money : {{money}}</p>
<p>Date : {{date}}</p>
<a href="{% url 'ManMon:mainpage'%}" class="circleBtn">{{"back to main page"}}</a>
</html>

ManMon/templates/ManMon/saveType.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ManMon/style.css' %}" />
<html>
<h1>You save:{{save_type}}</h1>
<a href="{% url 'ManMon:mainpage' %}" class="circleBtn"> back to main page</a>
</body>
</html>

ManMon/templates/ManMon/upload.html
<!DOCTYPE html>
<html>
<body>

<form action={% url 'ManMon:uploaded'%} method="ppst">
  <input type="file" name="file" accept="image/*">
  <input type="submit">
</form>



</body>
</html>