mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('ManMon.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^addQues/$', views.addQues, name='addQues'),
    url(r'^saveQues/$', views.saveQues, name='saveQues'),
    url(r'^(?P<question_id>[0-9]+)/addChoice/$', views.addChoice, name='addChoice'),
    url(r'^(?P<question_id>[0-9]+)/saveChoice/$', views.saveChoice, name='saveChoice'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils import timezone
from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def addQues(request):
    return render(request,"polls/addQuest.html",'')

def addChoice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,"polls/addChoice.html",{'question': question})

def saveQues(request):
    error_message = 0 
    try:
        question = request.POST['question']
    except:
        error_message = 1
        question = ""
    else:
            q = Question(question_text=question, pub_date=timezone.now())
            q.save()
    return render(request,"polls/saveQuest.html",{"question":question, "error_message":error_message})

def saveChoice(request, question_id):
    error_message = 0 
    try:
        choice = request.POST['choice']
    except:
        error_message = 1
        choice = ""
    else:
            q = Question.objects.get(id=question_id)
            q.choice_set.create(choice_text=choice, votes=0)
    return render(request,"polls/saveChoice.html",{"choice":choice, "error_message":error_message})

polls/templates/polls/addChoice.html
<!DOCTYPE html>
<html>
<body bgcolor="#00afff" >
<h1>Add Choice</h1>
<h2>your question,you want to add choice is :{{ question.question_text }}</h2>

<form action="{% url 'polls:saveChoice' question.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="choice" />
    <input type="submit" value="add choice" /><br>
</form>
</body>
</html>

polls/templates/polls/addQuest.html
<!DOCTYPE html>
<html>
<body bgcolor="#00afff" >
    <h1>Let add question</h1>

    <form action="{% url 'polls:saveQues' %}" method="post">
        {% csrf_token %}
        <input type="text" name="question" />
        <input type="submit" value="add question" />
        <br><a href="{% url 'polls:index' %}">back</a>
    </form>
</body>
</html>

polls/templates/polls/delQues.html
<html>
<body bgcolor="#00afff" >

{% if latest_question_list %}
    <ul>
    <table border=1 align="center" >
    {% for question in latest_question_list %}
        <tr >
            <td >
                <li><a  href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a></li>
           </td>
        </tr>  
    {% endfor %}
    </table>
    </ul>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<body bgcolor="#00afff" >
<h1>{{ question.question_text }}</h1>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<table border=1>
{% for choice in question.choice_set.all %}
<tr>
    <td>
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <th><label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br /></th>
    </td>
</tr>
{% endfor %}
</table>
<input type="submit" value="Vote" />
<br><a href="{% url 'polls:addChoice' question.id %}" >{{"Add Choice"}}</a>
<br><a href="{% url 'polls:index' %}">back</a>
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>

<body bgcolor="#00afff" >

<h1 style = " font-size:250%;text-align:center;"> My Polls</h1>
{% if latest_question_list %}
    <ul>
    <table border=1 align="center" >
    <a href="{% url 'polls:addQues' %}" ><h1 style = "text-align:center;">{{"Add Question"}}</h1></a>

    {% for question in latest_question_list %}
        <tr >
            <td >
                <li><a  href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a></li>
           </td>
        </tr>  
    {% endfor %}
</table>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<head>
<h1>{{ question.question_text }}</h1>
<body bgcolor="#00afff" >
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br><a href="{% url 'polls:index' %}">Back to vote the other question</a>
</body>
</head>

polls/templates/polls/saveChoice.html
<!DOCTYPE html>
<html>
<body bgcolor="#00afff" >
    {% if error_message %}
        <h1> Please,insert your choice</h1>
    {% else %}
        <h1> choice has been add</h1>
        <br>{{choice}}
    {% endif %}
    <br><a href="{% url 'polls:index' %}">back</a>
</body>
</html>

polls/templates/polls/saveQuest.html
<!DOCTYPE html>
<html>
<body bgcolor="#00afff" >
    {% if error_message %}
        <h1> You have to fill all empty field</h1>
    {% else %}
        <h1> Question has been add</h1>
        <br>{{question}}
    {% endif %}

<a herf="{% url 'polls:addQues' %}">Do you want to add another question?</a>
</body>
</html>